- name: include plan vars
  include_vars:
    file: "{{ _apb_plan_id }}.yml"
- name: generate b62 hash
  shell: "16to62 {{ params_hash }}"
  register: command_output
- name: set fact
  set_fact:
    stack_suffix: "{{ command_output.stdout }}"
- name: generate cidrs
  block:
  - name: generate cidrs
    shell: "getcidrs {{ CidrSize }} {{ NumberOfAvailabilityZones }} {{ VpcId }} {{ region }}"
    register: command_output
  - name: set fact
    set_fact:
      CidrBlocks: "{{ command_output.stdout }}"
  when: CidrBlocks == "auto"
- name: generate azs
  block:
  - name: generate azs
    shell: "getazs {{ NumberOfAvailabilityZones }} {{ region }}"
    register: command_output
  - name: set fact
    set_fact:
      AvailabilityZones: "{{ command_output.stdout }}"
  when: AvailabilityZones == "auto"
- name: Remove RedShift Cluster
  cloudformation:
    stack_name: "apb-redshift-{{ stack_suffix }}"
    state: "absent"
    region: "{{ region }}"
