AWSTemplateFormatVersion: 2010-09-09
Description: ' Redshift Template for Production Databases'
Parameters:
  ApplicationName:
    Description: >-
      This will be set as the value for the "APPLICATION_NAME" tag on all
      supported resources
    Type: String
  VpcId:
    Description: The ID of the VPC to launch the RDS instance into
    Type: 'AWS::EC2::VPC::Id'
  NumberOfAvailabilityZones:
    Description: >-
      Quantity of subnets to use, if selecting more than 2 the region this stack
      is in must have at least that many Availability Zones
    Type: String
    Default: '3'
    AllowedValues:
      - '2'
      - '3'
      - '4'
      - '5'
  PreferredMaintenanceWindowDay:
    Description: The day of the week which RDS maintenance will be performed
    Type: String
    Default: Mon
    AllowedValues:
      - Mon
      - Tue
      - Wed
      - Thu
      - Fri
      - Sat
      - Sun
  PreferredMaintenanceWindowStartTime:
    Description: >-
      The weekly start time in UTC for the RDS maintenance window, must be less
      than PreferredMaintenanceWindowEndTime and cannot overlap with
      PreferredBackupWindow
    Type: String
    Default: '04:00'
    AllowedValues:
      - '00:00'
      - '01:00'
      - '02:00'
      - '03:00'
      - '04:00'
      - '05:00'
      - '06:00'
      - '07:00'
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
      - '13:00'
      - '14:00'
      - '15:00'
      - '16:00'
      - '17:00'
      - '18:00'
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
  PreferredMaintenanceWindowEndTime:
    Description: >-
      The weekly end time in UTC for the RDS maintenance window, must be more
      than PreferredMaintenanceWindowEndTime and cannot overlap with
      PreferredBackupWindow
    Type: String
    Default: '06:00'
    AllowedValues:
      - '00:00'
      - '01:00'
      - '02:00'
      - '03:00'
      - '04:00'
      - '05:00'
      - '06:00'
      - '07:00'
      - '08:00'
      - '09:00'
      - '10:00'
      - '11:00'
      - '12:00'
      - '13:00'
      - '14:00'
      - '15:00'
      - '16:00'
      - '17:00'
      - '18:00'
      - '19:00'
      - '20:00'
      - '21:00'
      - '22:00'
  AvailabilityZones:
    Description: >-
      list of availability zones to use, must be the same quantity as specified
      in NumberOfAvailabilityZones
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  CidrBlocks:
    Description: >-
      comma seperated list of CIDR blocks to place RDS into, must be the same
      quantity as specified in NumberOfAvailabilityZones
    Type: CommaDelimitedList
    Default: '172.31.129.0/25,172.31.129.128/25,172.31.130.0/25'
  AccessCidr:
    Description: CIDR block to allow to connect to database
    Type: String
  MasterUsername:
    Description: Master Cluster Username
    Type: String
  NodeType:
    Description: The node type that is provisioned for this cluster.
    Type: String
    AllowedValues:
      - dc1.large
      - dc1.8xlarge
      - ds1.xlarge
      - ds1.8xlarge
      - ds2.xlarge
      - ds2.8xlarge
    Default: dc1.large
  NumberOfNodes:
    Description: >-
      The number of compute nodes in the cluster. If you specify multi-node for
      the ClusterType parameter, you must specify a number greater than 1. You
      can not specify this parameter for a single-node cluster. min 2 max 32 
    Type: String
    Default: '3'
  MasterUserPassword:
    Description: Master user Cluster Password
    Type: String
    NoEcho: 'true'
  ClusterType:
    Description: >-
      The type of cluster. Specify single-node or multi-node (default).  Number
      of nodes must be greater than 1 for multi-node
    Type: String
    AllowedValues:
      - single-node
      - multi-node
    Default: multi-node
  AllowVersionUpgrade:
    Description: >-
      When a new version of Amazon Redshift is released, tells whether upgrades
      can be applied to the engine that is running on the cluster. The upgrades
      are applied during the maintenance window. The default value is True. 
    Type: String
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'
  StorageEncrypted:
    Description: Indicates whether the Cluster storage is encrypted.
    Type: String
    Default: 'True'
    AllowedValues:
      - 'True'
      - 'False'
  BackupRetentionPeriod:
    Description: >-
      The number of days during which automatic DB snapshots are retained.
      Setting 0 disables automatic snapshots, maximum value is 35
    Type: Number
    Default: '35'
    MinValue: '0'
    MaxValue: '35'
  PortNumber:
    Description: The port number for the Cluster to listen on
    Type: Number
    Default: '5439'
    MinValue: '1150'
    MaxValue: '65535'
  PubliclyAccessible:
    Description: Indicates whether the Cluster is an Internet-facing instance.
    Type: String
    Default: 'False'
    AllowedValues:
      - 'True'
      - 'False'
  UseElasticIP:
    Description: 'For public accessable clusters which require a static IP, assign a EIP'
    Type: String
    Default: 'False'
    AllowedValues:
      - 'True'
      - 'False'
  LogBucketName:
    Description: >-
      Must be a valid S3 Bucket in same Region, if no bucket is provided audit
      logging will not be enabled for this cluster
    Type: String
  DBName:
    Description: The name of the database to create when the DB instance is created.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '^[a-zA-Z0-9]*$'
    ConstraintDescription: must contain from 1 to 64 alphanumeric characters.
Conditions:
  3az: !Or 
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '3'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '4'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '5'
  4az: !Or 
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '4'
    - !Equals 
      - !Ref NumberOfAvailabilityZones
      - '5'
  5az: !Equals 
    - !Ref NumberOfAvailabilityZones
    - '5'
  UseEIP: !Equals 
    - !Ref UseElasticIP
    - 'True'
  EncryptStorage: !Equals 
    - !Ref StorageEncrypted
    - 'True'
  EnableLogging: !Not 
    - !Equals 
      - !Ref LogBucketName
      - ''
Resources:
  KMSKey:
    Condition: EncryptStorage
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Sub 'Application: ${ApplicationName} Database: ${DBName}'
      Enabled: 'true'
      EnableKeyRotation: 'true'
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
              - 'kms:GenerateRandom'
            Resource: '*'
  ClusterParameterGroup:
    Type: 'AWS::Redshift::ClusterParameterGroup'
    Properties:
      ParameterGroupFamily: redshift-1.0
      Description: !Sub 'Application: ${ApplicationName} Database: ${DBName}'
      Parameters:
        - ParameterName: enable_user_activity_logging
          ParameterValue: 'true'
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
  ClusterSubnetGroup:
    Type: 'AWS::Redshift::ClusterSubnetGroup'
    Properties:
      Description: !Sub 'Application: ${ApplicationName} Database: ${DBName}'
      SubnetIds:
        - !Ref ClusterSubnet1
        - !Ref ClusterSubnet2
        - !If 
          - 3az
          - !Ref ClusterSubnet3
          - !Ref 'AWS::NoValue'
        - !If 
          - 4az
          - !Ref ClusterSubnet4
          - !Ref 'AWS::NoValue'
        - !If 
          - 5az
          - !Ref ClusterSubnet5
          - !Ref 'AWS::NoValue'
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
  ClusterSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 0
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 1
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet3:
    Condition: 3az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 2
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 2
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet4:
    Condition: 4az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 3
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 3
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSubnet5:
    Condition: 5az
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select 
        - 4
        - !Ref AvailabilityZones
      VpcId: !Ref VpcId
      CidrBlock: !Select 
        - 4
        - !Ref CidrBlocks
      Tags:
        - Key: APPLICATION_NAME
          Value: !Ref ApplicationName
  ClusterSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub >-
        Allow Client connections to Application: ${ApplicationName} Cluster:
        ${DBName}
      VpcId: !Ref VpcId
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref PortNumber
          ToPort: !Ref PortNumber
          CidrIp: !Ref AccessCidr
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0
  Cluster:
    Type: 'AWS::Redshift::Cluster'
    Properties:
      AllowVersionUpgrade: !Ref AllowVersionUpgrade
      AutomatedSnapshotRetentionPeriod: !Ref BackupRetentionPeriod
      ClusterParameterGroupName: !Ref ClusterParameterGroup
      ClusterSubnetGroupName: !Ref ClusterSubnetGroup
      ClusterType: !Ref ClusterType
      DBName: !Ref DBName
      ElasticIp: !If 
        - UseEIP
        - !Ref ClusterEIP
        - !Ref 'AWS::NoValue'
      Encrypted: !Ref StorageEncrypted
      KmsKeyId: !If 
        - EncryptStorage
        - !GetAtt 
          - KMSKey
          - Arn
        - !Ref 'AWS::NoValue'
      LoggingProperties: !If 
        - EnableLogging
        - BucketName: !Ref LogBucketName
        - !Ref 'AWS::NoValue'
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: !Ref NodeType
      NumberOfNodes: !Ref NumberOfNodes
      Port: !Ref PortNumber
      PreferredMaintenanceWindow: !Sub >-
        ${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowStartTime}-${PreferredMaintenanceWindowDay}:${PreferredMaintenanceWindowEndTime}
      PubliclyAccessible: !Ref PubliclyAccessible
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
      VpcSecurityGroupIds:
        - !Ref ClusterSecurityGroup
  ClusterEIP:
    Condition: UseEIP
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: VPC
Outputs:
  EndpointAddress:
    Value: !GetAtt 
      - Cluster
      - Endpoint.Address
