- name: Provision Redshift
  hosts: localhost
  gather_facts: true
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no

  - role: ansibleplaybookbundle.asb-modules

  - role: provision-redshift-apb-openshift
