- name: Launch Redshift
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-redshift-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/RedShiftCluster.yml"
   template_parameters:
     ApplicationName: "{{ ApplicationName }}"
     VpcId: "{{ VpcId }}"
     NumberOfAvailabilityZones: "{{ NumberOfAvailabilityZones | string }}"
     PreferredMaintenanceWindowDay: "{{ PreferredMaintenanceWindowDay }}"
     PreferredMaintenanceWindowStartTime: "{{ PreferredMaintenanceWindowStartTime }}"
     PreferredMaintenanceWindowEndTime: "{{ PreferredMaintenanceWindowEndTime }}"
     AvailabilityZones: "{{ AvailabilityZones }}"
     CidrBlocks: "{{ CidrBlocks }}"
     AccessCidr: "{{ AccessCidr }}"
     MasterUsername: "{{ MasterUsername }}"
     MasterUserPassword: "{{ MasterUserPassword }}"
     StorageEncrypted: "{{ StorageEncrypted }}"
     BackupRetentionPeriod: "{{ BackupRetentionPeriod | string }}"
     PortNumber: "{{ PortNumber | string }}"
     PubliclyAccessible: "{{ PubliclyAccessible }}"
     DBName: "{{ DBName }}"

     NodeType: "{{ NodeType }}"
     NumberOfNodes: "{{ NumberOfNodes }}"
     ClusterType: "{{ ClusterType }}"
     UseElasticIP: "{{ UseElasticIP }}"
     LogBucketName: "{{ LogBucketName }}"
     AllowVersionUpgrade: "{{ AllowVersionUpgrade }}"

   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-redshift"
     Description: "{{ ansible_user_id }} redshift {{ ApplicationName }}"
  register: redshift


- name: Check for Redshift CloudFormation error logs
  debug:
    var: redshift.log
