- name: Launch Redshift
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-redshift-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/RedShiftCluster.yml"
   template_parameters:
     ApplicationName: "{{ ApplicationName }}"
     VpcId: "{{ VpcId }}"
     NumberOfAvailabilityZones: "{{ NumberOfAvailabilityZones | string }}"
     PreferredMaintenanceWindowDay: "{{ PreferredMaintenanceWindowDay }}"
     PreferredMaintenanceWindowStartTime: "{{ PreferredMaintenanceWindowStartTime }}"
     PreferredMaintenanceWindowEndTime: "{{ PreferredMaintenanceWindowEndTime }}"
     AvailabilityZones: "{{ AvailabilityZones }}"
     CidrBlocks: "{{ CidrBlocks }}"
     AccessCidr: "{{ AccessCidr }}"
     MasterUsername: "{{ MasterUsername }}"
     MasterUserPassword: "{{ MasterUserPassword }}"
     StorageEncrypted: "{{ StorageEncrypted | string }}"
     BackupRetentionPeriod: "{{ BackupRetentionPeriod | string }}"
     PortNumber: "{{ PortNumber | string }}"
     PubliclyAccessible: "{{ PubliclyAccessible | string }}"
     DBName: "{{ DBName }}"
     NodeType: "{{ NodeType }}"
     NumberOfNodes: "{{ NumberOfNodes }}"
     ClusterType: "{{ ClusterType }}"
     UseElasticIP: "{{ UseElasticIP | string }}"
     LogBucketName: "{{ LogBucketName }}"
     AllowVersionUpgrade: "{{ AllowVersionUpgrade | string }}"
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-redshift"
     Description: "{{ ansible_user_id }} redshift {{ ApplicationName }}"
  register: redshift
- name: Check for CloudFormation error logs
  debug:
    var: redshift.log
- name: Encode bind credentials
  asb_encode_binding:
    fields:
      REDSHIFT_ENDPOINT: "{{ redshift.stack_outputs.EndpointAddress }}"
      REDSHIFT_PORT: "{{ PortNumber | string }}"
      REDSHIFT_USERNAME: "{{ MasterUsername }}"
      REDSHIFT_PASSWORD: "{{ MasterUserPassword }}"

  when: redshift.log | length < 1